name: Build telemt for OpenBSD aarch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile in OpenBSD VM
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.8"
          arch: aarch64
          usesh: true
          sync: sshfs
          envs: 'RUSTFLAGS'
          prepare: |
            pkg_add rust
          run: |
            cargo build --release
        env:
          RUSTFLAGS: "-C target-cpu=cortex-a53 -C target-feature=+aes,+pmull,+sha2,+sha1,+crc -C opt-level=3"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telemt-openbsd-aarch64
          path: target/release/telemt
          retention-days: 7
